services:
  - type: web
    name: douane-burkina-faso
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
